# Generated by Django 4.2.6 on 2024-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_analysis', '0002_remove_dnasequence_description_dnasequence_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequence',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
