# Generated by Django 4.2.6 on 2024-02-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dna_analysis', '0003_alter_dnasequence_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sequence1', to='dna_analysis.dnasequence')),
                ('sequence2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sequence2', to='dna_analysis.dnasequence')),
            ],
        ),
    ]
